### Get all products
GET http://localhost:5274/api/Product
Accept: application/json

###

### Get product by id
GET http://localhost:5274/api/Product/2
Accept: application/json

###

### Create product
POST http://localhost:5274/api/Product
Content-Type: application/json

{
  "name": "Test Product",
  "price": 999
}

###

### Update product
PUT http://localhost:5274/api/Product/1
Content-Type: application/json

{
  "id": 1,
  "name": "Updated Product",
  "price": 888
}

###

### Delete product
DELETE http://localhost:5274/api/Product/1
