@ProductApi_HostAddress = http://localhost:5274

### Get all products
GET {{ProductApi_HostAddress}}/api/Product
Accept: application/json

###

### Get product by id
GET {{ProductApi_HostAddress}}/api/Product/1
Accept: application/json

###

### Create product
POST {{ProductApi_HostAddress}}/api/Product
Content-Type: application/json

{
  "name": "胡蘿蔔",
  "price": 50,
  "Description": "超大條胡蘿蔔",
  "CategoryId": 2
}

###

### Update product
PUT {{ProductApi_HostAddress}}/api/Product/1
Content-Type: application/json

{
  "id": 1,
  "name": "Updated Product",
  "price": 888
}

###

### Delete product
DELETE {{ProductApi_HostAddress}}/api/Product/2

###

### Search product
GET {{ProductApi_HostAddress}}/api/Product/search?minPrice=100&maxPrice=500

###

### Search product
GET {{ProductApi_HostAddress}}/api/Product/category
